#!/usr/bin/tcsh
clear
if ($3 == "X-c" ) then
  echo "   a  b  c  d  e  f  g  h"
  cat memboard | sed 'N;N;N;N;N;N;N;s/\n/  /g' | sed '=' | sed 'N;s/\n/  /g;' | sed -f sedfile
  echo "\n-------------------------\n"
  endif
cat memboard | sed -n " $1 bL;$2 bL;s/[A-Z]/?/;:L p" > f3
echo "   a  b  c  d  e  f  g  h"
cat f3 | sed 'N;N;N;N;N;N;N;s/\n/  /g' | sed '=' | sed 'N;s/\n/  /g;' | sed -f sedfile | grep --color "[^A-Z0-9?_]"
echo
set x = `cat f3 | sed -n '/[^?_]/p' | uniq -c | sed -n 's/[ ]*2 [^?_]/1/p'`
if ( $x == 1 ) cat memboard | sed "$1 bL ; $2 bL ;b;:L s/[A-Z]/_/;" > f3
exit $x
