#!/usr/bin/tcsh
echo  ABCDEFGHIJKLMNOPQRSTUVWX | grep -on "[A-X]" | tr -d "1" | tee letters | tr "A-Z" "a-z" >> letters
sort -R letters | tr "a-z\n:" "A-Z, " > memboard
set x = 0
set y = 0
set counter = 0
while 1
	./displayboard $x $y $1
	if( X$? == X1 )then
		cat memboard | tr `head -1 match_list| tr -cd "A-Z"` "_" > temp
		cat temp > memboard
		grep -E "( _,){48}" memboard >&/dev/null && echo "Mission complete!\nMove : $counter" && exit
	endif
	./getchoice 0
	set x = $?
	./displayboard $x 0 $1
	./getchoice $x
	set y = $?
	@ counter++
end
